/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial - Basics', // category title that matches the label in _category_.json
      items: [
        {
          type: 'autogenerated', // autogenerate nav according to file structure and sidebar_position
          dirName: 'tutorial-basics' // directory name inside docs
        }
      ]
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras'
        }
      ]
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = {
  sidebars,
  ...require("./docs/schema/sidebar-schema")
}
