/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

};

module.exports = {
  sidebars,
  rateService: [
    {
      type: "autogenerated",
      dirName: "rate-service",
    }
  ],
  rateManagerService: [
    {
      type: "autogenerated",
      dirName: "rate-manager-service",
    }
  ],
  orderViewSidebar: [
    {
      type: "autogenerated",
      dirName: "order-view-service",
    },
  ],
  labelService: [
    {
      type: "autogenerated",
      dirName: "label-service",
    },
  ],
}
