/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
};

module.exports = {
  sidebars,
  Rating: [
    {
      type: 'category',
      label: 'Rates',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'rate'
        }
      ]
    },
    {
      type: 'link',
      label: 'Rates API',
      href: 'https://dev.shipperhq.com/rate-service/'
    }
  ],
  ShippingInsights: [
    {
      type: 'category',
      label: 'Insights',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'insight'
        }
      ]
    },
    {
      type: 'link',
      label: 'Insights API',
      href: 'https://dev.shipperhq.com/order-view-service/'
    }
  ],
  Label: [
    {
      type: 'category',
      label: 'Labels',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'label'
        }
      ]
    }
  ],
}
